version: '3'
services:
  caching-middleware:
    image: caching-middleware:latest
    container_name: caching-middleware
    restart: always
    ports: 
      - '8080:8080'
    volumes:
      - ./app:/app
      - /mnt/cache/files:/app/file
